package com.eg.ride.exception.model;

public enum ErrorCode {
  HTTP_MESSAGE_NOT_READABLE,
  WRONG_REQUEST_BODY,
  DATA_NOT_FOUND,
  RIDE_IN_PROGRESS,
  RIDE_NOT_FOUND,
  INCORRECT_RIDE_STATUS,
  STATUS_UPDATE_FAILED,
  WRONG_USER_TYPE,
  ACCESS_DENIED,
  UNKNOWN_EXCEPTION
}
